name: Node CI
on:
    push:
        branches: [develop, staging]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup-node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: building-code-develop
              if: contains(github.ref, 'develop')
              run: |
                  pnpm install
                  pnpm build
            - name: pushing-code-develop
              if: contains(github.ref, 'develop')
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEVELOPMENT_HOST }}
                  key: ${{ secrets.DEVELOPMENT_PRIVATE_KEY }}
                  username: ${{ secrets.DEVELOPMENT_USERNAME }}
                  source: 'out'
                  target: '/var/www/calilio/calilio-website/html'

            - name: building-code-staging
              if: contains(github.ref, 'staging')
              run: |
                  pnpm install
                  pnpm build
            - name: pushing-code-staging
              if: contains(github.ref, 'staging')
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.STAGING_HOST }}
                  key: ${{ secrets.STAGING_PRIVATE_KEY }}
                  username: ${{ secrets.STAGING_USERNAME }}
                  source: 'out'
                  target: '/var/www/calilio/calilio-website/html'
